#!/bin/bash

year=2023
day=$(date +%-d)
dir=day$day
url="https://adventofcode.com/$year/day/$day"
src=$dir/main.awk

mkdir $dir

curl --cookie $(cat ~/aoc_cookie) $url/input > $dir/input
xclip -selection primary -o > $dir/sample

echo "#! /usr/bin/awk -f" > $src
chmod +x $src
emacsclient -n -r $src
